Add rewards
moondance-labs/tanssi-symbiotic pull request #14
Opened 2024-12-20 18:31 UTC by NindoK

This PR:
- [ ] refactors the repo to divide between contracts and interfaces more clearly
- [ ] Introduces rewards for both operators and stakers.

2025-01-16 11:52 UTC, 0xvgg requested changes

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/middleware/Middleware.sol
> +    uint48 private constant INSTANT_SLASHER_TYPE = 0;
why not enum? it's 2 different values of the same type SlashType

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/middleware/Middleware.sol
> +            , // Dunno what to do with it xD
leave "TODO:  xxxx" of any future work

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +            if (amount == 0) {
confusing. use another variable, don't override variables.

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +            if (amount == 0) {
the block is if (amount > 0), but here you check for if (amount == 0) which shouldn't happen, but you have overrideen the input var - no,no

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +            s_balance[epoch].tokensPerPoint = amount / totalPointsToken; // To change the math. Check it's not zero
add TODO for any future work

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        // This should be double checked
add TODO for any future work

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        amount = totalPointsClaimable * s_balance[epoch].tokensPerPoint * 10 ** 18; //Is it fine to use 10**18 here? Should we get the decimals for each token?
add TODO for any future work

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        //!Comment 1: Math here is important. Please double check if this is what we want!!
if it's important, explain the intent of the math. we want: XXXX

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        uint256 operatorAmount = amount.mulDiv(20, 100); // 20% of the rewards to the operator
this should be configurable by the owner of the middleware. create variable and a setter guarded by onlyOwner

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        uint256 claimed_ = s_claimed[epoch][recipient]; // this can beecome a bool.
explain why it can become a bool

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +            unchecked {
why ++i is not in the for statement?

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +        //!Comment 1 Should we add that rewards are gonna expire after 1 month?
add TODO

2025-01-16 11:52 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +                rewardsPerEpoch;
what does rewardsPerEpoch; do?

2025-01-16 11:52 UTC, 0xvgg commented on src/interfaces/rewarder/IODefaultStakerRewards.sol
> +pragma solidity ^0.8.0;
0.8.25 - align solidity version for the whole project

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +    bytes public constant REWARDS_ADDITIONAL_DATA =
explain what these values represent

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +    bytes32 public constant REWARDS_ROOT = 0x4b0ddd8b9b8ec6aec84bcd2003c973254c41d976f6f29a163054eec4e7947810;
explain what this root represents

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +    bytes32 public constant ALICE_KEY = 0x0404040404040404040404040404040404040404040404040404040404040404;
can we have dynamic key provided by the testing framework?

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +        feeToken = new MockFeeToken("Test", 100); //Extreme but to test that's a possibility
what is extreme? explain

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +        proof[0] = 0x27e610a11a547f210646001377ae223bc6bce387931f8153624d21f6478512d2;
what this proof means? is it somehow relates to REWARDS_ROOT? why not in const

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +        proof[0] = 0xffe610a11a547f210646001377ae223bc6bce387931f8153624d21f6478512d2;
what this proof means? is it somehow relates to REWARDS_ROOT? why not in const

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +            hex"000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000
why is it bad? what did you change?

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +            hex"000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000
if this is broken REWARDS_ADDITIONAL_DATA, then make it such, e.g. REWARDS_ADDITIONAL_DATA[12] = 4; which will override a particular byte of the data and it's clear that you're breaking it

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +        bytes32 slot = keccak256(abi.encode(epoch, uint256(5))); // 5 is mapping slot number
5 is mapping slot number of what?

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +        vm.store(address(stakerRewards), slot, bytes32(uint256(AMOUNT_TO_DISTRIBUTE / 10)));
why it's 10 here?

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +        bytes32 slot = keccak256(abi.encode(uint48(0), uint256(2))); // 1 is mapping slot
why you're working with slots? can we have a view method?

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +            hex"0000000000000000000000000000000000000000000000056bc75e2d6310000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000
if this is broken REWARDS_ADDITIONAL_DATA, then make it such, e.g. REWARDS_ADDITIONAL_DATA[12] = 4; which will override a particular byte of the data and it's clear that you're breaking it

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +            hex"0000000000000000000000000000000000000000000000056bc75e2d6310000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000
if this is broken REWARDS_ADDITIONAL_DATA, then make it such, e.g. REWARDS_ADDITIONAL_DATA[12] = 4; which will override a particular byte of the data and it's clear that you're breaking it

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +            hex"0000000000000000000000000000000000000000000000056bc75e2d6310000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000
better yet, create a helper method _scrambledata(data)

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +            hex"0000000000000000000000000000000000000000000000056bc75e2d6310000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000
better yet, create a helper method _scrambledata(data)

2025-01-16 11:52 UTC, 0xvgg commented on test/unit/Rewards.t.sol
> +            hex"000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000
better yet, create a helper method _scrambledata(data)

2025-01-16 23:28 UTC, NindoK commented on test/unit/Rewards.t.sol
> +        bytes32 slot = keccak256(abi.encode(uint48(0), uint256(2))); // 1 is mapping slot
Because I'm manipulating the state and mocking values. Otherwise I need to follow the whole flow from distributeRewards to claimRewards and for every scenario change these values and it would become very tedious . In thsi way I'm creating the exact scenario that I want

2025-01-16 23:28 UTC, NindoK commented on test/unit/Rewards.t.sol
> +        vm.store(address(stakerRewards), slot, bytes32(uint256(AMOUNT_TO_DISTRIBUTE / 10)));
I'm saving 10 ethers inside the value. It's to say this person can claim only 1/10 of the amount distributed

2025-01-16 23:30 UTC, NindoK commented on test/unit/Rewards.t.sol
> +        bytes32 slot = keccak256(abi.encode(epoch, uint256(5))); // 5 is mapping slot number
It's the storage slot number of the variable `_s_activeSharesCache`

2025-01-16 23:32 UTC, NindoK commented on test/unit/Rewards.t.sol
> +        bytes32 slot = keccak256(abi.encode(epoch, uint256(5))); // 5 is mapping slot number
Added comments to avoid confusion

2025-01-17 00:02 UTC, NindoK commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +            if (amount == 0) {
Also I don't think changing would make sense. The code is highly optimized as follow and it makes sense. Reason being:

1. Amount is the amount that should be distributed
2. If the amount after the transfer is not the same amount should differ somehow
3. If it's 0 that's critical and should never happen
4. We should not check for different value, because there are tokens that have fees on transfer

2025-01-17 00:03 UTC, NindoK commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +            unchecked {
Because it's an optimization since we know it can't go past a specific value

2025-01-17 00:05 UTC, NindoK commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +                rewardsPerEpoch;
Left it there by mistake. Nice catch

2025-01-17 00:06 UTC, NindoK commented on src/interfaces/rewarder/IODefaultStakerRewards.sol
> +pragma solidity ^0.8.0;
It's a Library hence it's better to leave it as ^0.8.0. Then the contract is at 0.8.25

2025-01-17 00:12 UTC, NindoK commented on test/unit/Rewards.t.sol
> +        feeToken = new MockFeeToken("Test", 100); //Extreme but to test that's a possibility
The fee. It's just to test an extreme scenario in tests in which the final amount is 0 and thus the revert is triggered

2025-01-17 00:26 UTC, NindoK commented on test/unit/Rewards.t.sol
> +    bytes32 public constant ALICE_KEY = 0x0404040404040404040404040404040404040404040404040404040404040404;
Done

2025-01-17 08:50 UTC, girazoki commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +    mapping(uint48 epoch => mapping(address account => uint256 amount)) public s_claimed;
ah I see where you are going. You are considering this epoch to be the network epoch right? and for every "network epoch" you will keep adding when we receive rewards corresponding to that epoch, and then substract when people claim. Am I right here?

Please let me know

2025-01-17 08:54 UTC, girazoki commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +    mapping(uint48 epoch => mapping(address account => uint256 amount)) public s_claimed;
But this is not going to work I believe. Here is the reason:

- we are sending the rewards with: `total_inflated`, `total_points`, `tanssi_epoch`, `middleware_network_epoch` and `reward_root`. Remember the last 2 can be different, one can be larger than the other for instance. What you know for sure is that the rewards will be sent once per `tanssi_epoch`.

- You dont accumulate rewards per operator when you receive that information. You just get the root. That  means that this variable needs to be a boolean and the epoch has to be the `tanssi_epoch` necessarily

2025-01-17 08:57 UTC, girazoki commented on src/contracts/middleware/Middleware.sol
> +            uint256 timestamp,
![image](https://github.com/user-attachments/assets/8e78e36c-1dea-4a89-a055-f4d85ca4c31a)

Yes you are missing the era index. This is the tanssi-epoch. Essentially, everything needs to be indexed by that

2025-01-17 08:58 UTC, girazoki commented on src/contracts/middleware/Middleware.sol
> +    mapping(uint48 epoch => mapping(address operator => uint256 amount)) public s_operatorStakeCache;
This needs to be the tanssi era index. Everything will be indexed by that. That is the only "attachment" you have to tanssi whatsoever. That means that we also need a mapping between tanssi-era-index -> network_epoch

2025-01-17 09:00 UTC, girazoki commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        amount = totalPointsClaimable * s_balance[epoch].tokensPerPoint * 10 ** 18; //! TODO Is it fine to use 10**18 here? We are saying that are all IERC20 with 18 decimals. What if we use USDC as
the balance will already be with the appropriate decimals, why are we multiplying by 10^18?

2025-01-17 09:00 UTC, girazoki commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        uint256 claimed_ = s_claimed[epoch][recipient]; //TODO: This can become a bool. uint256 it's better even UI wise as we would know exactly how much was claimed instead of querying 2 times the
Not having a boolean allows someont to claim twice if I am not mistaken

2025-01-17 09:01 UTC, girazoki commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +        uint48 epoch,
again, tanssi-era

2025-01-20 18:40 UTC, 0xvgg requested changes

2025-01-20 18:40 UTC, 0xvgg commented on src/contracts/middleware/Middleware.sol
> +        if (slasherType == uint256(SlasherType.INSTANT)) {
can we avoid this casting by making SlasherType.INSTANT uint256?

2025-01-20 18:40 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +            if (amount == 0) {
it's not a matter of maount being amount, it's a matter of overriding the input param - which is not nice and confusing.

2025-01-20 18:40 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        uint256 claimed_ = s_claimed[epoch][recipient]; //TODO: This can become a bool. uint256 it's better even UI wise as we would know exactly how much was claimed instead of querying 2 times the
let's not consider UI right now. UI can always do ETL to transform the values to the needed format

2025-01-20 18:40 UTC, 0xvgg commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        amount = totalPointsClaimable * s_balance[epoch].tokensPerPoint * 10 ** 18; //! TODO Is it fine to use 10**18 here? We are saying that are all IERC20 with 18 decimals. What if we use USDC as
agree, 
s_balance[epoch].amount was set with amount, which we received in distributeRewards
function distributeRewards(
        uint48 epoch,
        uint256 amount,

but @NindoK overrode the value of amount, which is a separate comment. in anyway, s_balance should be in the correct type set in distributeRewards

2025-01-20 22:33 UTC, NindoK commented on src/contracts/middleware/Middleware.sol
> +        if (slasherType == uint256(SlasherType.INSTANT)) {
Nope

2025-01-20 22:35 UTC, NindoK commented on src/contracts/middleware/Middleware.sol
> +    mapping(uint48 epoch => mapping(address operator => uint256 amount)) public s_operatorStakeCache;
I think these shouldn't be touched as they are relative to ethereum epoch. It's not related to rewards or anything

2025-01-20 22:35 UTC, NindoK commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +        uint48 epoch,
I'm thinking this should remain epoch since for stakers they have the eraindex intrinsically in the array of rewards. Let's talk tomorrow about it real quick

2025-01-21 08:21 UTC, ParthDesai commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        s_claimed[epoch][recipient] = amount;
shouldn't you add this amount to previous value of `s_claimed`?

2025-01-22 09:11 UTC, 0xvgg requested changes

2025-01-22 09:11 UTC, 0xvgg commented on src/contracts/middleware/Middleware.sol
>                  emit InvalidSlashTimeframe(epoch, operator, amount);
InvalidSlashTimeframe error is only for specific vault among s_vaults, so it will be unclear which one. add to InvalidSlashTimeframe vault address/id

2025-01-22 09:11 UTC, 0xvgg commented on src/contracts/middleware/Middleware.sol
> +        if (address(s_gateway) == address(0)) {
yes, this is ownerOnly

why do we have operatorKeys setter as array? each operator should set his own key, no?

2025-01-22 09:21 UTC, girazoki commented on src/contracts/middleware/Middleware.sol
>              revert Middleware__UnknownSlasherType();
same here, changing this in my PR. so dont worry about this

2025-01-22 09:22 UTC, girazoki commented on src/contracts/middleware/Middleware.sol
> +        if (address(s_gateway) == address(0)) {
why this has to be restricted? I think it can be sent by anyone no?

2025-01-22 09:36 UTC, NindoK commented on src/contracts/middleware/Middleware.sol
> +        if (address(s_gateway) == address(0)) {
Where is this setter?

2025-01-22 12:11 UTC, girazoki commented on src/contracts/middleware/Middleware.sol
> +    // TODO: THIS MUST BE RESTRICTED EITHER TO OWNER OR SOMEONE ELSE
remove TODO

2025-01-22 12:14 UTC, girazoki commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +            IERC20(i_token).safeTransferFrom(msg.sender, address(this), amount);
what is this? this is wrong no?

2025-01-22 12:33 UTC, girazoki commented on src/contracts/rewarder/ODefaultStakerRewards.sol
> +        if (epochTs >= Time.timestamp()) {
comment

2025-01-22 12:53 UTC, girazoki approved these changes
Please let's add comments on the main logics of `claimRewards` and `distributeRewards`, in both rewarders

2025-01-22 12:53 UTC, girazoki commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +            IERC20(i_token).safeTransferFrom(msg.sender, address(this), amount);
it's correct

2025-01-22 12:54 UTC, girazoki commented on src/contracts/rewarder/ODefaultOperatorRewards.sol
> +        _distributeRewardsToStakers(input.epoch, input.eraIndex, stakerAmount, recipient, middlewareAddress, input.data);
epoch should not be in the input, but rather, we should fetch it from storage. Otherwise it can be gamed

2025-01-22 15:41 UTC, merged